version: '3'

services:
  ctf-challenge:
    image: localhost:56156/ctf-challenge
    build:
      context: ../../../
      dockerfile: Challenges/ctf-category/ctf-folder/Dockerfile
    ports:
      - "80:80"
    networks:
      nw0:
    deploy:
      resources:
        limits:
          memory: 200m
          cpus: '0.1'
    environment:
      FLAG: "9c2c9f937a52aeea5dcaf7885dd835ee"

networks:
  nw0:
    external: true
