name: UMass-CTF-Challenge

docker_image: localhost:56156/CTF-Challenge

description: |
  author: [Haijie Qin](https://github.com/ygbull)

  Example Instruction:
  This challenge tests the ability to manipulate HTTP headers, bypass file upload restrictions, and exploit simple PHP scripts to access sensitive files. 
  Participants must navigate through a series of web-based forms, modify file content, and finally retrieve a flag from a supposedly secure location.

  Step 1:
    Modify the Referer header to gain access to the main page.
  Step 2:
    Bypass the file type verification to upload a malicious script that can read server files.
  Step 3:
    Execute the uploaded script to retrieve the flag and submit it.

value: 250
category: Web Exploitation
flag: CTF_SDaT{9c2c9f937a52aeea5dcaf7885dd835ee}

hints:
  - {
    content: "The server checks for a specific Referer header (umass.edu) to allow access. Can you spoof this header to gain access?",
    cost: 10
  }
  - {
    content: "Although the server restricts uploads to PDFs by checking MIME types and magic numbers, can you disguise a PHP script as a PDF?",
    cost: 20
  }
  - {
    content: "Files are uploaded with their names base64-encoded and made URL safe. Think about how you can use this method to predict the path of your uploaded file.",
    cost: 30
  }
